"""Real-time monitoring for online contrastive learning during search.

Tracks learning progress, experience buffer health, model update behavior,
gradient norms, loss values, and correlates learning with search performance.

Non-intrusive: reads from OnlineLearningManager and search statistics
without modifying any learning or search behavior.

Usage:
    monitor = LearningMonitor()

    # After each model update:
    monitor.record_update(manager, search_stats)

    # After each given clause:
    monitor.record_selection(was_ml=True, was_productive=True, search_stats)

    # Generate report:
    print(monitor.report())
"""

from __future__ import annotations

import logging
import math
import time
from collections import deque
from dataclasses import dataclass, field
from enum import IntEnum, auto
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from pyladr.search.statistics import SearchStatistics

logger = logging.getLogger(__name__)


# ── Alert severity ────────────────────────────────────────────────────────


class AlertSeverity(IntEnum):
    """Severity levels for learning alerts."""

    INFO = auto()
    WARNING = auto()
    CRITICAL = auto()


@dataclass(frozen=True, slots=True)
class LearningAlert:
    """Alert generated by the learning monitor."""

    severity: AlertSeverity
    category: str  # e.g., "loss_spike", "buffer_imbalance", "convergence"
    message: str
    timestamp: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)


# ── Model update snapshot ─────────────────────────────────────────────────


@dataclass(slots=True)
class UpdateSnapshot:
    """Snapshot of metrics at a model update point."""

    update_id: int = 0
    timestamp: float = 0.0

    # Loss metrics
    avg_loss: float = 0.0
    loss_delta: float = 0.0  # Change from previous update

    # Gradient metrics
    grad_norm: float = 0.0
    max_grad: float = 0.0

    # Buffer state
    buffer_size: int = 0
    buffer_productive: int = 0
    buffer_unproductive: int = 0
    productive_ratio: float = 0.0

    # Model version
    model_version: int = 0
    was_accepted: bool = True
    was_rollback: bool = False

    # Search state at update time
    given_count: int = 0
    kept_count: int = 0
    search_keep_rate: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "update_id": self.update_id,
            "timestamp": self.timestamp,
            "avg_loss": self.avg_loss,
            "loss_delta": self.loss_delta,
            "grad_norm": self.grad_norm,
            "max_grad": self.max_grad,
            "buffer_size": self.buffer_size,
            "buffer_productive": self.buffer_productive,
            "buffer_unproductive": self.buffer_unproductive,
            "productive_ratio": self.productive_ratio,
            "model_version": self.model_version,
            "was_accepted": self.was_accepted,
            "was_rollback": self.was_rollback,
            "given_count": self.given_count,
            "kept_count": self.kept_count,
            "search_keep_rate": self.search_keep_rate,
        }


# ── Selection tracking ────────────────────────────────────────────────────


@dataclass(slots=True)
class SelectionWindow:
    """Tracks selection outcomes over a sliding window."""

    window_size: int = 100
    _ml_outcomes: deque[bool] = field(default_factory=lambda: deque(maxlen=100))
    _trad_outcomes: deque[bool] = field(default_factory=lambda: deque(maxlen=100))
    total_ml: int = 0
    total_trad: int = 0
    total_ml_productive: int = 0
    total_trad_productive: int = 0

    def __post_init__(self) -> None:
        self._ml_outcomes = deque(maxlen=self.window_size)
        self._trad_outcomes = deque(maxlen=self.window_size)

    def record_ml(self, productive: bool) -> None:
        self._ml_outcomes.append(productive)
        self.total_ml += 1
        if productive:
            self.total_ml_productive += 1

    def record_traditional(self, productive: bool) -> None:
        self._trad_outcomes.append(productive)
        self.total_trad += 1
        if productive:
            self.total_trad_productive += 1

    @property
    def ml_window_rate(self) -> float:
        if not self._ml_outcomes:
            return 0.0
        return sum(self._ml_outcomes) / len(self._ml_outcomes)

    @property
    def trad_window_rate(self) -> float:
        if not self._trad_outcomes:
            return 0.0
        return sum(self._trad_outcomes) / len(self._trad_outcomes)

    @property
    def ml_overall_rate(self) -> float:
        if self.total_ml == 0:
            return 0.0
        return self.total_ml_productive / self.total_ml

    @property
    def trad_overall_rate(self) -> float:
        if self.total_trad == 0:
            return 0.0
        return self.total_trad_productive / self.total_trad

    @property
    def ml_advantage(self) -> float:
        """ML productivity rate minus traditional rate (recent window)."""
        return self.ml_window_rate - self.trad_window_rate


# ── Buffer health metrics ─────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class BufferHealth:
    """Health assessment of the experience buffer."""

    size: int = 0
    capacity: int = 0
    fill_ratio: float = 0.0
    productive_ratio: float = 0.0
    is_balanced: bool = True  # productive/unproductive ratio in acceptable range
    is_stale: bool = False  # No new data recently
    staleness_seconds: float = 0.0
    status: str = "healthy"  # "healthy", "imbalanced", "stale", "empty", "critical"

    def to_dict(self) -> dict[str, Any]:
        return {
            "size": self.size,
            "capacity": self.capacity,
            "fill_ratio": self.fill_ratio,
            "productive_ratio": self.productive_ratio,
            "is_balanced": self.is_balanced,
            "is_stale": self.is_stale,
            "staleness_seconds": self.staleness_seconds,
            "status": self.status,
        }


# ── Learning monitor ──────────────────────────────────────────────────────


class LearningMonitor:
    """Comprehensive monitoring for online contrastive learning.

    Collects metrics from the online learning system and search engine,
    detects anomalies, and generates reports for debugging and analysis.

    Non-intrusive: only reads data, never modifies learning or search state.

    Usage:
        monitor = LearningMonitor()

        # After model update:
        monitor.record_update(
            update_id=1, accepted=True, avg_loss=0.5,
            grad_norm=0.02, buffer_size=500,
            buffer_productive=200, buffer_unproductive=300,
            model_version=1, search_stats=stats,
        )

        # After each selection:
        monitor.record_selection(ml_guided=True, productive=True)

        # Generate reports:
        print(monitor.report())
        health = monitor.assess_buffer_health(buffer_size=500, capacity=5000,
                                               productive=200, unproductive=300)
    """

    __slots__ = (
        "_updates", "_alerts", "_selections", "_start_time",
        "_last_update_time", "_loss_ema", "_grad_norm_ema",
        "_balance_low", "_balance_high", "_stale_threshold",
    )

    def __init__(
        self,
        balance_low: float = 0.15,
        balance_high: float = 0.85,
        stale_threshold: float = 60.0,
    ) -> None:
        """Initialize learning monitor.

        Args:
            balance_low: Minimum acceptable productive ratio in buffer.
            balance_high: Maximum acceptable productive ratio in buffer.
            stale_threshold: Seconds without update before buffer is "stale".
        """
        self._updates: list[UpdateSnapshot] = []
        self._alerts: list[LearningAlert] = []
        self._selections = SelectionWindow()
        self._start_time = time.monotonic()
        self._last_update_time = self._start_time
        self._loss_ema: float = 0.0
        self._grad_norm_ema: float = 0.0
        self._balance_low = balance_low
        self._balance_high = balance_high
        self._stale_threshold = stale_threshold

    # ── Recording ─────────────────────────────────────────────────────

    def record_update(
        self,
        update_id: int,
        accepted: bool,
        avg_loss: float = 0.0,
        grad_norm: float = 0.0,
        max_grad: float = 0.0,
        buffer_size: int = 0,
        buffer_productive: int = 0,
        buffer_unproductive: int = 0,
        model_version: int = 0,
        was_rollback: bool = False,
        search_stats: SearchStatistics | None = None,
    ) -> UpdateSnapshot:
        """Record metrics from a model update event.

        Returns the snapshot for inspection/logging.
        """
        now = time.monotonic() - self._start_time
        self._last_update_time = time.monotonic()

        # Compute loss delta
        loss_delta = 0.0
        if self._updates:
            loss_delta = avg_loss - self._updates[-1].avg_loss

        # Search metrics
        given_count = 0
        kept_count = 0
        keep_rate = 0.0
        if search_stats is not None:
            given_count = search_stats.given
            kept_count = search_stats.kept
            if search_stats.generated > 0:
                keep_rate = search_stats.kept / search_stats.generated

        # Productive ratio
        prod_ratio = 0.0
        if buffer_size > 0:
            prod_ratio = buffer_productive / buffer_size

        snap = UpdateSnapshot(
            update_id=update_id,
            timestamp=now,
            avg_loss=avg_loss,
            loss_delta=loss_delta,
            grad_norm=grad_norm,
            max_grad=max_grad,
            buffer_size=buffer_size,
            buffer_productive=buffer_productive,
            buffer_unproductive=buffer_unproductive,
            productive_ratio=prod_ratio,
            model_version=model_version,
            was_accepted=accepted,
            was_rollback=was_rollback,
            given_count=given_count,
            kept_count=kept_count,
            search_keep_rate=keep_rate,
        )
        self._updates.append(snap)

        # Check for anomalies BEFORE updating EMAs (so spike isn't smoothed)
        self._check_loss_anomaly(snap)
        self._check_gradient_anomaly(snap)
        self._check_rollback_frequency()

        # Update EMAs after anomaly checks
        alpha = 0.3
        if self._loss_ema == 0.0:
            self._loss_ema = avg_loss
        else:
            self._loss_ema = alpha * avg_loss + (1 - alpha) * self._loss_ema

        if self._grad_norm_ema == 0.0:
            self._grad_norm_ema = grad_norm
        else:
            self._grad_norm_ema = alpha * grad_norm + (1 - alpha) * self._grad_norm_ema

        return snap

    def record_selection(self, ml_guided: bool, productive: bool) -> None:
        """Record a clause selection outcome.

        Args:
            ml_guided: Whether the selection used ML scoring.
            productive: Whether the selection led to a productive outcome.
        """
        if ml_guided:
            self._selections.record_ml(productive)
        else:
            self._selections.record_traditional(productive)

    # ── Buffer health ─────────────────────────────────────────────────

    def assess_buffer_health(
        self,
        buffer_size: int,
        capacity: int,
        productive: int,
        unproductive: int,
    ) -> BufferHealth:
        """Assess the health of the experience buffer.

        Returns a BufferHealth object with status and diagnostics.
        """
        if buffer_size == 0:
            health = BufferHealth(
                size=0, capacity=capacity,
                status="empty",
            )
            self._emit_alert(
                AlertSeverity.WARNING, "buffer_empty",
                "Experience buffer is empty — no training data available",
            )
            return health

        fill_ratio = buffer_size / capacity if capacity > 0 else 0.0
        prod_ratio = productive / buffer_size

        # Balance check
        balanced = self._balance_low <= prod_ratio <= self._balance_high

        # Staleness check
        staleness = time.monotonic() - self._last_update_time
        stale = staleness > self._stale_threshold

        # Determine status
        status = "healthy"
        if not balanced and stale:
            status = "critical"
        elif not balanced:
            status = "imbalanced"
        elif stale:
            status = "stale"

        health = BufferHealth(
            size=buffer_size,
            capacity=capacity,
            fill_ratio=fill_ratio,
            productive_ratio=prod_ratio,
            is_balanced=balanced,
            is_stale=stale,
            staleness_seconds=staleness,
            status=status,
        )

        if not balanced:
            self._emit_alert(
                AlertSeverity.WARNING, "buffer_imbalance",
                f"Buffer productive ratio {prod_ratio:.2f} outside "
                f"[{self._balance_low}, {self._balance_high}]",
                {"productive_ratio": prod_ratio},
            )

        if stale:
            self._emit_alert(
                AlertSeverity.WARNING, "buffer_stale",
                f"No model update for {staleness:.1f}s",
                {"staleness_seconds": staleness},
            )

        return health

    # ── Anomaly detection ─────────────────────────────────────────────

    def _check_loss_anomaly(self, snap: UpdateSnapshot) -> None:
        """Check for loss spikes or divergence."""
        if len(self._updates) < 3:
            return

        # Loss spike: > 3x the EMA
        if self._loss_ema > 0 and snap.avg_loss > 3.0 * self._loss_ema:
            self._emit_alert(
                AlertSeverity.WARNING, "loss_spike",
                f"Loss spike at update {snap.update_id}: "
                f"{snap.avg_loss:.4f} (EMA: {self._loss_ema:.4f})",
                {"loss": snap.avg_loss, "ema": self._loss_ema},
            )

        # Loss divergence: monotonically increasing over last 5 updates
        if len(self._updates) >= 5:
            recent = self._updates[-5:]
            losses = [u.avg_loss for u in recent]
            if all(losses[i] < losses[i + 1] for i in range(len(losses) - 1)):
                self._emit_alert(
                    AlertSeverity.CRITICAL, "loss_divergence",
                    f"Loss has been increasing for {len(losses)} consecutive updates",
                    {"losses": losses},
                )

    def _check_gradient_anomaly(self, snap: UpdateSnapshot) -> None:
        """Check for gradient anomalies."""
        if snap.grad_norm == 0.0:
            return

        # Gradient explosion: > 10x the EMA
        if self._grad_norm_ema > 0 and snap.grad_norm > 10.0 * self._grad_norm_ema:
            self._emit_alert(
                AlertSeverity.CRITICAL, "gradient_explosion",
                f"Gradient norm {snap.grad_norm:.4f} >> EMA {self._grad_norm_ema:.4f}",
                {"grad_norm": snap.grad_norm, "ema": self._grad_norm_ema},
            )

        # Vanishing gradients
        if snap.grad_norm < 1e-8 and len(self._updates) > 3:
            self._emit_alert(
                AlertSeverity.WARNING, "vanishing_gradient",
                f"Gradient norm near zero: {snap.grad_norm:.2e}",
                {"grad_norm": snap.grad_norm},
            )

    def _check_rollback_frequency(self) -> None:
        """Check if rollbacks are happening too frequently."""
        if len(self._updates) < 5:
            return

        recent = self._updates[-5:]
        rollbacks = sum(1 for u in recent if u.was_rollback)
        if rollbacks >= 3:
            self._emit_alert(
                AlertSeverity.CRITICAL, "excessive_rollbacks",
                f"{rollbacks} rollbacks in last 5 updates — "
                f"learning may be unstable",
                {"rollback_count": rollbacks},
            )

    def _emit_alert(
        self,
        severity: AlertSeverity,
        category: str,
        message: str,
        details: dict[str, Any] | None = None,
    ) -> None:
        """Emit a learning alert."""
        alert = LearningAlert(
            severity=severity,
            category=category,
            message=message,
            timestamp=time.monotonic() - self._start_time,
            details=details or {},
        )
        self._alerts.append(alert)
        log_fn = logger.warning if severity >= AlertSeverity.WARNING else logger.info
        log_fn("LearningAlert [%s] %s: %s", severity.name, category, message)

    # ── Queries ───────────────────────────────────────────────────────

    @property
    def update_count(self) -> int:
        return len(self._updates)

    @property
    def updates(self) -> list[UpdateSnapshot]:
        return list(self._updates)

    @property
    def alerts(self) -> list[LearningAlert]:
        return list(self._alerts)

    @property
    def selections(self) -> SelectionWindow:
        return self._selections

    @property
    def rollback_count(self) -> int:
        """Number of updates that were rolled back."""
        return sum(1 for u in self._updates if u.was_rollback)

    def recent_alerts(self, limit: int = 10) -> list[LearningAlert]:
        """Return the most recent alerts."""
        return list(self._alerts)[-limit:]

    def loss_history(self) -> list[float]:
        """Return loss values for all recorded updates."""
        return [u.avg_loss for u in self._updates]

    def grad_norm_history(self) -> list[float]:
        """Return gradient norm values for all recorded updates."""
        return [u.grad_norm for u in self._updates]

    def productivity_history(self) -> list[float]:
        """Return buffer productive ratios for all recorded updates."""
        return [u.productive_ratio for u in self._updates]

    def get_alerts_by_severity(
        self, severity: AlertSeverity,
    ) -> list[LearningAlert]:
        """Get alerts at or above a given severity."""
        return [a for a in self._alerts if a.severity >= severity]

    def get_alerts_by_category(self, category: str) -> list[LearningAlert]:
        """Get alerts for a specific category."""
        return [a for a in self._alerts if a.category == category]

    # ── Reporting ─────────────────────────────────────────────────────

    def report(self) -> str:
        """Generate a comprehensive learning monitoring report."""
        lines = [
            "=" * 60,
            "ONLINE LEARNING MONITOR REPORT",
            "=" * 60,
        ]

        # Update summary
        if not self._updates:
            lines.append("No model updates recorded.")
            lines.append("=" * 60)
            return "\n".join(lines)

        lines.append(f"Total updates: {len(self._updates)}")
        accepted = sum(1 for u in self._updates if u.was_accepted)
        rolled_back = sum(1 for u in self._updates if u.was_rollback)
        lines.append(f"  Accepted: {accepted}, Rolled back: {rolled_back}")

        # Loss trend
        losses = self.loss_history()
        if losses:
            lines.append("")
            lines.append("Loss:")
            lines.append(f"  First: {losses[0]:.4f}")
            lines.append(f"  Last:  {losses[-1]:.4f}")
            lines.append(f"  Min:   {min(losses):.4f}")
            lines.append(f"  Max:   {max(losses):.4f}")
            lines.append(f"  EMA:   {self._loss_ema:.4f}")

        # Gradient norms
        grads = [g for g in self.grad_norm_history() if g > 0]
        if grads:
            lines.append("")
            lines.append("Gradient norms:")
            lines.append(f"  Mean: {sum(grads) / len(grads):.6f}")
            lines.append(f"  Max:  {max(grads):.6f}")
            lines.append(f"  EMA:  {self._grad_norm_ema:.6f}")

        # Selection comparison
        sel = self._selections
        if sel.total_ml > 0 or sel.total_trad > 0:
            lines.append("")
            lines.append("Selection performance:")
            if sel.total_ml > 0:
                lines.append(
                    f"  ML-guided:    {sel.total_ml} selections, "
                    f"{sel.ml_overall_rate:.3f} productivity "
                    f"(window: {sel.ml_window_rate:.3f})"
                )
            if sel.total_trad > 0:
                lines.append(
                    f"  Traditional:  {sel.total_trad} selections, "
                    f"{sel.trad_overall_rate:.3f} productivity "
                    f"(window: {sel.trad_window_rate:.3f})"
                )
            if sel.total_ml > 0 and sel.total_trad > 0:
                adv = sel.ml_advantage
                label = "advantage" if adv >= 0 else "disadvantage"
                lines.append(f"  ML {label}: {adv:+.3f} (recent window)")

        # Search correlation
        if len(self._updates) >= 2:
            lines.append("")
            lines.append("Search correlation:")
            first_kr = self._updates[0].search_keep_rate
            last_kr = self._updates[-1].search_keep_rate
            delta = last_kr - first_kr
            lines.append(
                f"  Keep rate: {first_kr:.3f} -> {last_kr:.3f} "
                f"(delta: {delta:+.3f})"
            )

        # Alerts summary
        critical = self.get_alerts_by_severity(AlertSeverity.CRITICAL)
        warnings = [
            a for a in self._alerts
            if a.severity == AlertSeverity.WARNING
        ]
        if critical or warnings:
            lines.append("")
            lines.append(f"Alerts: {len(critical)} critical, {len(warnings)} warnings")
            for a in critical[-3:]:
                lines.append(f"  !!! [{a.category}] {a.message}")
            for a in warnings[-3:]:
                lines.append(f"   !  [{a.category}] {a.message}")

        lines.append("=" * 60)
        return "\n".join(lines)

    def to_csv_rows(self) -> list[dict[str, Any]]:
        """Export all update snapshots as list of dicts for CSV/DataFrame."""
        return [u.to_dict() for u in self._updates]
